### Get /
GET http://localhost:3000/api/books

### Create a post
POST http://localhost:3000/api/books/add
Content-Type: application/json

{
    "title": "Sad Bird still sing",
    "type": "bbbbb"
}

### Delete post
DELETE http://localhost:3000/api/books/delete/2
Content-Type: application/json



### Update a book
PUT http://localhost:3000/api/books/update/1
Content-Type: application/json

{
    "title": "To Kill a Mockingbird",
    "type": "Novel"
}